# Generated by Django 3.2.9 on 2024-07-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240702_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='close_time',
            field=models.DateTimeField(),
        ),
    ]
